<?php
require_once 'db_connect.php';

if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] !== 'admin') {
    header('Location: login.php');
    exit();
}


$report_data = [
    'total_users' => $conn->query("SELECT COUNT(*) as count FROM users")->fetch_assoc()['count'],
    'total_items' => $conn->query("SELECT COUNT(*) as count FROM items")->fetch_assoc()['count'],
    'items_by_status' => $conn->query("SELECT status, COUNT(*) as count FROM items GROUP BY status")->fetch_all(MYSQLI_ASSOC),
    'items_by_category' => $conn->query("SELECT category, COUNT(*) as count FROM items GROUP BY category")->fetch_all(MYSQLI_ASSOC),
    'claims_by_status' => $conn->query("SELECT status, COUNT(*) as count FROM claims GROUP BY status")->fetch_all(MYSQLI_ASSOC),
    'recent_activity' => $conn->query("SELECT COUNT(*) as count FROM items WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)")->fetch_assoc()['count']
];

$report_content = "College Lost & Found System Report\n";
$report_content .= "Generated: " . date('Y-m-d H:i:s') . "\n";
$report_content .= "Generated by: " . $_SESSION['user_name'] . "\n\n";
$report_content .= "SYSTEM STATISTICS:\n";
$report_content .= "Total Users: " . $report_data['total_users'] . "\n";
$report_content .= "Total Items: " . $report_data['total_items'] . "\n";
$report_content .= "Items Last 7 Days: " . $report_data['recent_activity'] . "\n\n";

$report_content .= "ITEMS BY STATUS:\n";
foreach ($report_data['items_by_status'] as $status) {
    $report_content .= "  " . $status['status'] . ": " . $status['count'] . "\n";
}

$report_content .= "\nITEMS BY CATEGORY:\n";
foreach ($report_data['items_by_category'] as $category) {
    $report_content .= "  " . $category['category'] . ": " . $category['count'] . "\n";
}

$report_content .= "\nCLAIMS BY STATUS:\n";
foreach ($report_data['claims_by_status'] as $claim) {
    $report_content .= "  " . $claim['status'] . ": " . $claim['count'] . "\n";
}


$report_file = 'reports/system_report_' . date('Y-m-d_H-i-s') . '.txt';
if (!is_dir('reports')) {
    mkdir('reports', 0755, true);
}
file_put_contents($report_file, $report_content);


require_once 'log_action.php';
log_action($conn, $_SESSION['user_id'], 'REPORT', 'system', 0, [], ['report_file' => $report_file]);

$_SESSION['success'] = "System report generated successfully";
header('Location: admin_management.php');
exit();
?>